spring.application.name=simpleWeb

spring.datasource.username=nobody
spring.datasource.password=1234
spring.datasource.url=jdbc:h2:mem:store
spring.datasource.driverClassName=org.h2.Driver

spring.jpa.show-sql=true